const express = require("express");
const router = express.Router();
const healthRoutes = require("./health.routes"); 
const authRoutes = require("./auth.routes"); 
const userRoutes = require("./client/user.routes");
const predictionRoutes = require("./client/prediction.routes");
const adminRoutes = require("./admin/admin.routes");
router.use("/health", healthRoutes);    
router.use("/auth", authRoutes);        
router.use("/user", userRoutes);        
router.use("/predict", predictionRoutes); 
router.use("/admin", adminRoutes);     
module.exports = router;